CREATE OR REPLACE PROCEDURE DDCKPAY_SP(DD_ID IN NUMBER,
                                       DD_AMT IN NUMBER,
                                       OUTPUT OUT VARCHAR2)
    IS

    LV_ROW      DD_PLEDGE%ROWTYPE;
    FINAL_PRICE NUMBER;
    INCORRECT EXCEPTION;
BEGIN
    SELECT *
    INTO LV_ROW
    FROM DD_PLEDGE
    WHERE IDPLEDGE = DD_ID;


    IF LV_ROW.PAYMONTHS = 0 THEN
        RAISE INCORRECT;
    END IF;

    FINAL_PRICE := LV_ROW.PLEDGEAMT / LV_ROW.PAYMONTHS;

    IF DD_AMT = FINAL_PRICE THEN
        OUTPUT := 'THE PAYMENT IS CORRECT';
    ELSIF DD_AMT != FINAL_PRICE THEN
        RAISE_APPLICATION_ERROR(-20050, 'Incorrect payment amount - planned payment = ' || FINAL_PRICE);
    END IF;

EXCEPTION
    WHEN INCORRECT THEN
        DBMS_OUTPUT.PUT_LINE('No payment information');
END DDCKPAY_SP;

DECLARE
    OUTPUT VARCHAR2(242);
BEGIN
    DDCKPAY_SP(104, 25, OUTPUT);
    DBMS_OUTPUT.PUT_LINE(OUTPUT);
END;